### ISSUE TITLE
Use of "ExpandedSourceTracking" feature in demo-scratch-def.json is causing the demo build to fail.

### ISSUE THREAD

**Issue by VivekMChawla** [sfdx-isv/fsc-demo-pack#1]
Discovered by Jaswinder.

Running `falcon:adk:install` with the flag `--falcondebug "ACTION:create-scratch-org"` yields debug output that shows the following error response when the Falcon engine is creating the scratch org.

`INVALID_INPUT: ExpandedSourceTracking is not a valid Features value.`

Editing this line should fix this:
https://github.com/sfdx-isv/fsc-demo-pack/blob/3fea3eb4afdec8b5775a07187bcd9ee077721040/config/demo-scratch-def.json#L11

**Comment by jrattanpal** [comment]
Removed that feature in commit: https://github.com/sfdx-isv/fsc-demo-pack/commit/43c587dd69e2c65c0a5ce76c41ca94a66f759f3b
