### ISSUE TITLE
Creation fails as FSC package is deprecated

### ISSUE THREAD

**Issue by rsoesemann** [sfdx-isv/fsc-demo-pack#3]
When I ran the installation it failed with that error:

> Your request to install package "Financial Services Cloud r216.1.0" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.
> 
> If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.
> 
> Organization: FSC Demo Pack (00D4E0000001XgJ)
> User: User User (0054E000004iIsV)
> Package: Financial Services Cloud (04t80000000jZjl)
> 
> Problem:
> 1. Package(03380000000U1CP) AppExchange Package is Deprecated
> The AppExchange package has been deprecated and can no longer be installed.
> 
>        Please try installing a newer version, or contact the package owner directly to resolve.

**Comment by jrattanpal** [comment]
Please use https://github.com/Vchalem/fsc-demo-pack for latest updates.

**Comment by jrattanpal** [comment]
Issue is that FSC package version needs to be updated when FSC product team pushes out a new package upgrade.
