### ISSUE TITLE
1) Package(03380000000U1CP) AppExchange Package is Deprecated, Details: The AppExchange package has been deprecated and can no longer be installed.

### ISSUE THREAD

**Issue by sreenishkrishnan** [sfdx-isv/fsc-demo-pack#5]
I'm getting this error:
SfdxCliError: Installation of package 'Financial Services Cloud (Managed Package), Version 220.6' (04t1E000000y9ew) failed. Installation errors: 
1) Package(03380000000U1CP) AppExchange Package is Deprecated, Details: The AppExchange package has been deprecated and can no longer be installed.          Please try installing a newer version, or contact the package owner directly to resolve.

![image](https://user-images.githubusercontent.com/25716423/81251976-0bf7a900-9068-11ea-93c4-dccd4de8ebcf.png)

Can you advise how to resolve this?

**Comment by VivekMChawla** [comment]
@sreenishkrishnan - You need to update the package version IDs that are used inside of the `demo-recipe.json` file.

Follow the instructions in the README.md file in the https://github.com/sfdx-isv/fsc-demo-pack/tree/master/config directory for guidance on how to get the most recent FSC Package IDs.
