### ISSUE TITLE
Can't select correct devHub when working with multiple devHub's

### ISSUE THREAD

**Issue by lucas-saito** [sfdx-isv/fsc-demo-pack#8]
During devHub selection I always get a list of devHub's, but I can't see the correct one.

This issue occur when running sfdx falcon:adk:create or falcon:adk:clone

**Comment by VivekMChawla** [comment]
@lucas-saito can you share a screenshot of what you're seeing at `falcon:adk:create`?

**Comment by lucas-saito** [comment]
<img width="679" alt="screenshot_falcon" src="https://user-images.githubusercontent.com/50039126/85995445-83a9da80-b9fe-11ea-9054-0d29c931f2cb.png">

@VivekMChawla this is the list of devHubs I see. None is the one I want to use for this project.

**Comment by VivekMChawla** [comment]
@lucas-saito if you run `sfdx force:org:list` does the expected DevHub show up as "Connected"?

If yes, are you able to log into that org via `sfdx force:org:open -u YourDevHub` and successfully navigate to the "Scratch Org Infos" object and view any of your records there?

Alternatively, can you confirm you can create a scratch org using `sfdx force:org:create` using the DevHub that's not showing up on this list?

**Comment by lucas-saito** [comment]
@VivekMChawla I can run and see the expected DevHub as connected, and I'm also able to login and see scratch org info. After I create one scratch org from my devHub I was able to see it on the list. I'll continue with my testings now. Thanks.
